### ISSUE TITLE
Question sur les changements liés à Reborn

### ISSUE THREAD

**Issue by smonff** [raphaelgoetter/knacss-reborn#16]
Bonjour,

Je ne trouve pas de documentation à ce sujet: est-ce que un certain nombre de classes utilitaires telles que les `.alert` et `.alert--warning` et donc les `.btn--*` etc. on été retirés de Reborn?

Merci.

**Comment by smonff** [comment]
Si oui, ne faudrait-il pas créer un repository "historique" en mode archive avec le bug tracker fermé et n'acceptant pas de PR de façon à ce que au moins des projets reposant sur les anciennes versions puissent s'y référer? Car là, c'est un peu moyen en terme de rétrocompabilité, c'est à dire que on ne peut même pas s'appuyer sur des tags git qui marqueraient des versions 🤔

**Comment by raphaelgoetter** [comment]
Hello KNACSS Reborn n'a plus rien à voir avec KNACSS. Il n'y a aucune rétro-compatibilité ni historique.

- KNACSS est toujours dispo sur un repo dédié : https://github.com/alsacreations/KNACSS 
- KNACSS Reborn est hébegé ici et la doc est dispo : https://www.knacss.com/doc.html

**Comment by smonff** [comment]
Ok, merci pour cette réponse rapide. Je comprends mieux, c'est donc deux projets séparés. 

En toute honnêteté, ce n'est pas clair du tout pour les personnes qui ne suivent pas votre actualité de façon continue. Suggestions de présentation:

- passer le repository de `KNACSS` en *read-only* (dans les préférences, il y a une option d'Archivage pour celà)
- référencer `KNACSS` dans la doc et le README de KNACSS Reborn pour les personens qui chercheraient l'ancienne librairie

Personnellement, j'utilise `KNACSS` dans tous mes projet (à [IFOP](https://www.ifop.com)) et aussi pour des projets perso et là je viens de tenter de builder les SCSS pour réparer des choses "cassées" suite à des mises à jour. Peut être que j'ai mal lu, ou mal fait ma veille, mais voilà, si c'est arrivé à une personne, on peut imaginer que ça arrivera à d'autres.

Merci.

**Comment by smonff** [comment]
P.S: de mon côté, la confusion est plutôt venue [du site](https://www.knacss.com/): c'est toujours le même, mais le lien sur Github a changé. Peut être çà vaudrait le coup de rajouter un lien sur l'ancienne version quand même...
