### ISSUE TITLE
utilitaire pour display block

### ISSUE THREAD

**Issue by raphaelgoetter** [raphaelgoetter/knacss-reborn#3]
Il manque une classe utilitaire à knacss pour display: block

**Comment by blupdew** [comment]
Exemple d'usage : modifier le display par défaut d'éléments inline (entre autres) sans avoir à passer par une déclaration "custom".

**Comment by raphaelgoetter** [comment]
Corrigé dans les classes utilitaires de l'issue https://github.com/raphaelgoetter/knacss-reborn/issues/11
