### ISSUE TITLE
Ajouter une variable de spacer plus réduite

### ISSUE THREAD

**Issue by blupdew** [raphaelgoetter/knacss-reborn#7]
Il existe spacer-tiny ayant pour valeur 0.5rem, on peut avoir besoin d'une valeur encore plus réduite (disons 1/2 de spacer-tiny soit 0.25rem) pouvant se nommer par exemple spacer-nano.

**Comment by raphaelgoetter** [comment]
0.25rem correspond à 2.5 pixels.

**Comment by blupdew** [comment]
Ce qui passe bien en "fraction" de pixels, ou sur un écran hdpi.

**Comment by raphaelgoetter** [comment]
corrigé
