### ISSUE TITLE
Ajuster la valeur de spacer-tiny-plus

### ISSUE THREAD

**Issue by blupdew** [raphaelgoetter/knacss-reborn#8]
La variable spacer-tiny-plus correspond à 0.7rem, entre ses acolytes 0.5rem et 1rem.

Or les autres sont déclinées sur une échelle selon des proportions x2 ou x1.5

Il serait plus cohérent de lui donner la valeur 0.75rem.

```
$spacer-tiny             : .5rem  !default;
$spacer-tiny-plus        : .7rem !default;
$spacer-small            : 1rem !default;
$spacer-small-plus       : 1.5rem !default;
$spacer-medium           : 2rem !default;
$spacer-medium-plus      : 3rem !default;
```

**Comment by raphaelgoetter** [comment]
Oui, mais 0.75rem correspond à 7.5 pixels...

**Comment by blupdew** [comment]
Ce qui passe bien en "fraction" de pixels, ou sur un écran hdpi.

**Comment by raphaelgoetter** [comment]
Corrigé via l'issue https://github.com/raphaelgoetter/knacss-reborn/issues/11
